//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ESTILOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int id { get; set; }
        public decimal pago { get; set; }
        public decimal importe { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int id_usuario { get; set; }
        public int id_carrito { get; set; }
    
        public virtual carrito carrito { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
